---
---
#libraries
```{r}
library(tidyverse)
library(dplyr)
library(dslabs)
library(readxl)
library(ggplot2)
library(RColorBrewer)
library(tidyr)
library(openxlsx)
library(svglite)
library(rstatix)
```

#import figure 2 files
```{r}
setwd("/Users/Elly/Desktop/Whistler Lab/D3 Project/Behavior Experiments/")
All_Conditioned_place_data <- readxl::read_excel("All Conditioned place data.xlsx", 
                                         sheet = 3)

#sheet is 3 for sga cpa and 2 for coc cpp
cpa_all<- All_Conditioned_place_data

pref_combined <- data.frame(cpa_all %>%
                dplyr:: select(initial_pref, final_pref, mouse_id, drug, treatment, genotype) %>%
      rename(baseline = initial_pref, final = final_pref) %>%
      pivot_longer(cols = c(baseline, final), names_to = "pref", values_to = "percent"))
```

#Figure 2C (cloz cpa)
```{r}
acute_cloz <- data.frame(pref_combined) %>% filter(drug=="cloz") %>% 
  filter(genotype=="WT") %>%
  filter(treatment=="acute")

summary_df <- acute_cloz %>%
  group_by(pref, drug) %>%
  summarize(
    mean = mean(percent, na.rm = TRUE),
    sem = sd(percent, na.rm = TRUE) / sqrt(n()))

plot <- ggplot(acute_cloz, aes(x = pref)) +
  geom_bar(aes(y = percent, fill = drug, color = drug), 
           alpha = 0.5, 
           stat = "summary", 
           fun = "mean",
           width = 0.7) +
  geom_errorbar(data=summary_df, aes(ymin = mean - sem, ymax = mean + sem, color=drug),
                width = 0.2) +
  geom_point(aes(y = percent, fill = drug, color = drug), size = 2) +
  geom_path(aes(group = mouse_id, y = percent, color = drug), alpha = 0.7) +  
  theme_classic() +
  scale_color_manual(values = c("cloz" = "magenta4", "dmso"="gray40", "quet"="darkgreen")) +
  scale_fill_manual(values=c("cloz"="magenta4"))+
  scale_y_continuous(limits = c(0, 100), expand = expansion(mult = c(0, 0.02))) +
  ylab("Percent time on Drug side") +
  scale_x_discrete(labels = str_wrap(c("Baseline", "Final Preference"), width = 10)) +
theme(
    axis.text.x = element_text(size = 25, color = "black"),
    axis.ticks.x = element_blank(),
    axis.title.x = element_blank(),
    text = element_text(family = "Arial", size = 25),  # Set font to Arial
    plot.title = element_text(hjust = 0.5, family = "Arial"),  # Title font
    axis.line = element_line(size = 1.2),
    axis.text = element_text(family = "Arial"),  # Apply Arial to axis text
    axis.title = element_text(family = "Arial")  # Axis title in Arial
  ) +
  guides(fill = FALSE, color = FALSE)  # Remove legend for fill and color
  
  print(plot)
  
      # Set the working directory
setwd("/Users/Elly/Desktop/Kim Lab-Whistler Lab/D3 Behavior Manuscript/EPS files")

# Use Cairo EPS device
cairo_ps("fig 2c.eps", width = 5.2, height = 8, family = "ArialMT", pointsize = 12)

# Create the plot
print(plot)

# Close the Cairo EPS device
dev.off()

# Set the working directory
setwd("/Users/Elly/Desktop/Kim Lab-Whistler Lab/D3 Behavior Manuscript/PDF figures")

# Save the plot as a PDF
ggsave(
  filename = "fig_2C.pdf",
  plot = plot,
  device = cairo_pdf,
  width = 5.2,
  height = 8,
  units = "in",
  family = "ArialMT"
)
```

#Figure 2D (acute quet)
```{r}
acute_quet <- data.frame(pref_combined) %>% filter(drug=="quet") %>% 
  filter(genotype=="WT") %>%
  filter(treatment=="acute")

summary_df <- acute_quet %>%
  group_by(pref, drug) %>%
  summarize(
    mean = mean(percent, na.rm = TRUE),
    sem = sd(percent, na.rm = TRUE) / sqrt(n()))

plot <- ggplot (acute_quet, aes(x=pref)) +
  geom_bar(aes(y = percent, fill = drug, color = drug), 
           alpha = 0.5, 
           stat = "summary", 
           fun = "mean",
           width = 0.7) +
  geom_errorbar(data=summary_df, aes(ymin = mean - sem, ymax = mean + sem, color=drug),
                width = 0.2) +
  geom_point(aes(y = percent, fill = drug, color = drug), size = 2) +
  geom_path(aes(group = mouse_id, y = percent, color = drug), alpha = 0.7) +  
  theme_classic() +
  scale_color_manual(values = c("cloz" = "orange", "dmso"="gray40", "quet"="darkgreen")) +
  scale_fill_manual(values=c("quet"="darkgreen"))+
    scale_y_continuous(limits = c(0, 100), expand = expansion(mult = c(0, 0.02))) +
  ylab("Percent time on Drug side") +
  scale_x_discrete(labels = str_wrap(c("Baseline", "Final Preference"), width = 10)) +
theme(
    axis.text.x = element_text(size = 25, color = "black"),
    axis.ticks.x = element_blank(),
    axis.title.x = element_blank(),
    text = element_text(family = "Arial", size = 25),  # Set font to Arial
    plot.title = element_text(hjust = 0.5, family = "Arial"),  # Title font
    axis.line = element_line(size = 1.2),
    axis.text = element_text(family = "Arial"),  # Apply Arial to axis text
    axis.title = element_text(family = "Arial")  # Axis title in Arial
  ) +
  guides(fill = FALSE, color = FALSE)  # Remove legend for fill and color
  
  print(plot)
  
      # Set the working directory
setwd("/Users/Elly/Desktop/Kim Lab-Whistler Lab/D3 Behavior Manuscript/EPS files")

# Use Cairo EPS device
cairo_ps("fig 2d.eps", width = 5.2, height = 8, family = "ArialMT", pointsize = 12)

# Create the plot
print(plot)

# Close the Cairo EPS device
dev.off()

# Set the working directory
setwd("/Users/Elly/Desktop/Kim Lab-Whistler Lab/D3 Behavior Manuscript/PDF figures")

# Save the plot as a PDF
ggsave(
  filename = "fig_2D.pdf",
  plot = plot,
  device = cairo_pdf,
  width = 5.2,
  height = 8,
  units = "in",
  family = "ArialMT"
)
```

#Figure 2B (dmso)
```{r}
acute_dmso <- pref_combined %>%
  filter(drug == "dmso", genotype == "WT", treatment == "acute") %>%
  group_by(pref, drug) %>%
  mutate(mean_percent = mean(percent, na.rm = TRUE)) %>%
  ungroup()

summary_df <- acute_dmso %>%
  group_by(pref, drug) %>%
  summarize(
    mean = mean(percent, na.rm = TRUE),
    sem = sd(percent, na.rm = TRUE) / sqrt(n()))

plot <- ggplot(acute_dmso, aes(x=pref)) +
   geom_bar(aes(y = percent, fill = drug, color = drug), 
           alpha = 0.5, 
           stat = "summary", 
           fun = "mean", 
           width = 0.7) +
  geom_errorbar(data=summary_df, aes(ymin = mean - sem, ymax = mean + sem, color=drug),
                width = 0.2) +
  geom_point(aes(y = percent, fill = drug, color = drug), size = 2) +
  geom_path(aes(group = mouse_id, y = percent, color = drug), alpha = 0.7) +  
  theme_classic() +
  scale_color_manual(values = c("cloz" = "orange", "dmso"="gray40", "quet"="forestgreen")) +
  scale_fill_manual(values=c("dmso"="gray40"))+
    scale_y_continuous(limits = c(0, 100), expand = expansion(mult = c(0, 0.02))) +
  ylab("Percent time on Drug side") +
  scale_x_discrete(labels = str_wrap(c("Baseline", "Final Preference"), width = 10)) +
theme(
    axis.text.x = element_text(size = 25, color = "black"),
    axis.ticks.x = element_blank(),
    axis.title.x = element_blank(),
    text = element_text(family = "Arial", size = 25),  # Set font to Arial
    plot.title = element_text(hjust = 0.5, family = "Arial"),  # Title font
    axis.line = element_line(size = 1.2),
    axis.text = element_text(family = "Arial"),  # Apply Arial to axis text
    axis.title = element_text(family = "Arial")  # Axis title in Arial
  ) +
  guides(fill = FALSE, color = FALSE)  # Remove legend for fill and color

     # Set the working directory
setwd("/Users/Elly/Desktop/Kim Lab-Whistler Lab/D3 Behavior Manuscript/EPS files")

# Use Cairo EPS device
cairo_ps("fig 2B.eps", width = 5.2, height = 8, family = "ArialMT", pointsize = 12)

# Create the plot
print(plot)

# Close the Cairo EPS device
dev.off()

# Set the working directory
setwd("/Users/Elly/Desktop/Kim Lab-Whistler Lab/D3 Behavior Manuscript/PDF figures")

# Save the plot as a PDF
ggsave(
  filename = "fig_2B.pdf",
  plot = plot,
  device = cairo_pdf,
  width = 5.2,
  height = 8,
  units = "in",
  family = "ArialMT"
)
```
#Figure 2G(chronic quet)
```{r}
chronic_quet <- data.frame(pref_combined) %>% filter(drug=="quet") %>% 
  filter(genotype=="WT") %>%
  filter(treatment=="chronic")

summary_df <- chronic_quet %>%
  group_by(pref, drug) %>%
  summarize(
    mean = mean(percent, na.rm = TRUE),
    sem = sd(percent, na.rm = TRUE) / sqrt(n()))

plot <- ggplot(chronic_quet, aes(x = pref)) + 
  geom_bar(aes(y = percent, fill = drug, color = drug), 
           alpha = 0.5, 
           stat = "summary", 
           fun = "mean", 
           width=0.7) +
  geom_errorbar(data=summary_df, aes(ymin = mean - sem, ymax = mean + sem, color=drug),
                width = 0.2) +
  geom_point(aes(y = percent, fill = drug, color = drug), size = 2) +
  geom_path(aes(group = mouse_id, y = percent, color = drug), alpha = 0.7) +  
  theme_classic() +
  scale_color_manual(values = c("cloz" = "magenta4", "dmso"="gray40", "quet"="darkgreen")) +
  scale_fill_manual(values=c("cloz"="magenta4", "quet"="darkgreen"))+
    scale_y_continuous(limits = c(0, 100), expand = expansion(mult = c(0, 0.02))) +
  ylab("Percent time on Drug side \n post Pre-Treatment") +
  scale_x_discrete(labels = str_wrap(c("Baseline", "Final Preference"), width = 10)) +
theme(
    axis.text.x = element_text(size = 25, color = "black"),
    axis.ticks.x = element_blank(),
    axis.title.x = element_blank(),
    text = element_text(family = "Arial", size = 25),  # Set font to Arial
    plot.title = element_text(hjust = 0.5, family = "Arial"),  # Title font
    axis.line = element_line(size = 1.2),
    axis.text = element_text(family = "Arial"),  # Apply Arial to axis text
    axis.title = element_text(family = "Arial")  # Axis title in Arial
  ) +
  guides(fill = FALSE, color = FALSE)  # Remove legend for fill and color
  
  print(plot)
  
      # Set the working directory
setwd("/Users/Elly/Desktop/Kim Lab-Whistler Lab/D3 Behavior Manuscript/EPS files")

# Use Cairo EPS device
cairo_ps("fig 2g.eps", width = 5.2, height = 8, family = "ArialMT", pointsize = 12)

# Create the plot
print(plot)

# Close the Cairo EPS device
dev.off()

# Set the working directory
setwd("/Users/Elly/Desktop/Kim Lab-Whistler Lab/D3 Behavior Manuscript/PDF figures")

# Save the plot as a PDF
ggsave(
  filename = "fig_2G.pdf",
  plot = plot,
  device = cairo_pdf,
  width = 5.2,
  height = 8,
  units = "in",
  family = "ArialMT"
)
```

#Figure 2F (chronic cloz)
```{r}
chronic_cloz <- data.frame(pref_combined) %>% filter(drug=="cloz") %>% 
  filter(genotype=="WT") %>%
  filter(treatment=="chronic")

summary_df <- chronic_cloz %>%
  group_by(pref, drug) %>%
  summarize(
    mean = mean(percent, na.rm = TRUE),
    sem = sd(percent, na.rm = TRUE) / sqrt(n()))

plot <- ggplot (chronic_cloz, aes(x=pref)) +
  geom_bar(aes(y = percent, fill = drug, color = drug), 
           alpha = 0.5, 
           stat = "summary", 
           fun = "mean", 
           width = 0.7) +
  geom_errorbar(data=summary_df, aes(ymin = mean - sem, ymax = mean + sem, color=drug),
                width = 0.2) +
  geom_point(aes(y = percent, fill = drug, color = drug), size = 2) +
  geom_path(aes(group = mouse_id, y = percent, color = drug), alpha = 0.7) +  
  theme_classic() +
  scale_color_manual(values = c("cloz" = "magenta4", "dmso"="gray40", "quet"="darkgreen")) +
  scale_fill_manual(values=c("cloz"="magenta4"))+
    scale_y_continuous(limits = c(0, 100), expand = expansion(mult = c(0, 0.02))) +
  ylab("Percent time on Drug side \n post Pre-Treatment") +
  scale_x_discrete(labels = str_wrap(c("Baseline", "Final Preference"), width = 10)) +
theme(
    axis.text.x = element_text(size = 25, color = "black"),
    axis.ticks.x = element_blank(),
    axis.title.x = element_blank(),
    text = element_text(family = "Arial", size = 25),  # Set font to Arial
    plot.title = element_text(hjust = 0.5, family = "Arial"),  # Title font
    axis.line = element_line(size = 1.2),
    axis.text = element_text(family = "Arial"),  # Apply Arial to axis text
    axis.title = element_text(family = "Arial")  # Axis title in Arial
  ) +
  guides(fill = FALSE, color = FALSE)  # Remove legend for fill and color
  
  print(plot)
  
      # Set the working directory
setwd("/Users/Elly/Desktop/Kim Lab-Whistler Lab/D3 Behavior Manuscript/EPS files")

# Use Cairo EPS device
cairo_ps("fig 2f.eps", width = 5.2, height = 8, family = "ArialMT", pointsize = 12)

# Create the plot
print(plot)

# Close the Cairo EPS device
dev.off()

# Set the working directory
setwd("/Users/Elly/Desktop/Kim Lab-Whistler Lab/D3 Behavior Manuscript/PDF figures")

# Save the plot as a PDF
ggsave(
  filename = "fig_2F.pdf",
  plot = plot,
  device = cairo_pdf,
  width = 5.2,
  height = 8,
  units = "in",
  family = "ArialMT"
)
```
#Figure 2H (DF chronic)
```{r}
chronic_quet_df <- data.frame(pref_combined) %>% filter(drug=="quet") %>% 
  filter(genotype=="DF") %>%
  filter(treatment=="chronic")

summary_df <- chronic_quet_df %>%
  group_by(pref, drug) %>%
  summarize(
    mean = mean(percent, na.rm = TRUE),
    sem = sd(percent, na.rm = TRUE) / sqrt(n()))

plot <- ggplot (chronic_quet_df, aes(x=pref)) +
  geom_bar(aes(y = percent, fill = drug, color = drug), 
           alpha = 0.8, 
           stat = "summary", 
           fun = "mean", 
           width=0.7) +
  geom_errorbar(data=summary_df, aes(ymin = mean - sem, ymax = mean + sem, color=drug),
                width = 0.2) +
  geom_point(aes(y = percent, fill = drug, color = drug), size = 2, shape= 1) +
  geom_path(aes(group = mouse_id, y = percent, color = drug), alpha = 0.7) +  
  theme_classic() +
  scale_color_manual(values = c("cloz" = "magenta4", "dmso"="gray40", "quet"="darkgreen")) +
  scale_fill_manual(values=c("cloz"="magenta4", "quet"="white"))+
    scale_y_continuous(limits = c(0, 100), expand = expansion(mult = c(0, 0.02))) +
  ylab("Percent time on Drug side \n post Pre-Treatment") +
  scale_x_discrete(labels = str_wrap(c("Baseline", "Final Preference"), width = 10)) +
theme(
    axis.text.x = element_text(size = 25, color = "black"),
    axis.ticks.x = element_blank(),
    axis.title.x = element_blank(),
    text = element_text(family = "Arial", size = 25),  # Set font to Arial
    plot.title = element_text(hjust = 0.5, family = "Arial"),  # Title font
    axis.line = element_line(size = 1.2),
    axis.text = element_text(family = "Arial"),  # Apply Arial to axis text
    axis.title = element_text(family = "Arial")  # Axis title in Arial
  ) +
  guides(fill = FALSE, color = FALSE)  # Remove legend for fill and color
  
  print(plot)
  
      # Set the working directory
setwd("/Users/Elly/Desktop/Kim Lab-Whistler Lab/D3 Behavior Manuscript/EPS files")

# Use Cairo EPS device
cairo_ps("fig 2h.eps", width = 5.2, height = 8, family = "ArialMT", pointsize = 12)

# Create the plot
print(plot)

# Close the Cairo EPS device
dev.off()

# Set the working directory
setwd("/Users/Elly/Desktop/Kim Lab-Whistler Lab/D3 Behavior Manuscript/PDF figures")

# Save the plot as a PDF
ggsave(
  filename = "fig_2H.pdf",
  plot = plot,
  device = cairo_pdf,
  width = 5.2,
  height = 8,
  units = "in",
  family = "ArialMT"
)
```

#Figure 2 paired t test
```{r}
t_test_results <- list()

for (current_treatment in unique(pref_combined$treatment)) {
  for (current_genotype in unique(pref_combined$genotype)) {
    for (current_drug in unique(pref_combined$drug)) {
      
      # Subset data for the current treatment, genotype, and drug
      subset_data <- pref_combined[pref_combined$drug == current_drug & 
                                    pref_combined$genotype == current_genotype & 
                                    pref_combined$treatment == current_treatment, ]
      
      # Check if there are exactly two levels in the pref column
      if (length(unique(subset_data$pref)) == 2) {
        # Extract percent values for baseline and final
        baseline_values <- subset_data$percent[subset_data$pref == "baseline"]
        final_values <- subset_data$percent[subset_data$pref == "final"]
        
        # Check if we have equal lengths for paired t-test
        if (length(baseline_values) == length(final_values)) {
          # Perform the paired t-test
          t_test_result <- t.test(baseline_values, final_values, paired = TRUE)
          
          # Store results in the list
          t_test_results[[paste(current_genotype, current_drug, current_treatment, sep = "_")]] <- t_test_result
        }
      }
    }
  }
}

# Print the results
print(t_test_results)
```

#Figure S2 data upload
```{r}
cpp_long <- cpp_data %>%
  pivot_longer(
    cols = c(initial, final),
    names_to = "timepoint",
    values_to = "score"
  )

# make timepoint a factor so it's ordered Initial → Final
cpp_long$timepoint <- factor(cpp_long$timepoint, levels = c("initial", "final"))

# plot
plot <- ggplot(cpp_long, aes(x = timepoint, y = score, color = group)) +
  geom_point(size = 1, alpha = 0.6) +
  geom_path(aes(group = mouse_id), alpha = 0.6) +
  stat_summary(fun = mean, geom = "point", 
               aes(group = group, color=group),
               position = position_dodge(width = 0.2),
               shape = 18, size = 5, fill = "black") +
  theme_classic()

print(plot)

```
#Figure S2B
```{r}
dmso_cloz <- data.frame(cpp_long) %>% filter(group=="dmso-cloz")

summary_df <- dmso_cloz %>%
  group_by(timepoint, group) %>%
  summarize(
    mean = mean(score, na.rm = TRUE),
    sem = sd(score, na.rm = TRUE) / sqrt(n()),
    .groups = "drop")

plot <- ggplot(dmso_cloz, aes(x = timepoint)) +
  geom_bar(aes(y = score, fill = group, color = group, group = timepoint), 
           alpha = 0.5, 
           stat = "summary", 
           position = position_dodge(width = 0.7), 
           fun = "mean", 
           width=0.7) +
  geom_errorbar(data=summary_df, aes(ymin = mean - sem, ymax = mean + sem, color=group, group = timepoint),
                width = 0.2, position = position_dodge(width = 0.7),) +
  geom_path(aes(group = mouse_id, y = score, color = group), alpha = 0.8) +  
    geom_point(aes(y = score, fill = group, group = timepoint, color=group), size = 1, position = position_dodge(width = 0.7), alpha=0.8) +
  scale_color_manual(values = c("dmso-quet"= "forestgreen", "dmso-cloz"= "magenta4")) +
  scale_fill_manual(values = c("dmso-quet"= "forestgreen", "dmso-cloz"= "magenta4")) +
  theme_classic()  +
  scale_y_continuous(limits = c(0, 100), expand = expansion(mult = c(0, 0.02))) +
  ylab("Percent time on Drug side") +
  scale_x_discrete(labels = str_wrap(c("Baseline", "Final Preference"), width = 10)) +
theme(
    axis.text.x = element_text(size = 25, color = "black"),
    axis.ticks.x = element_blank(),
    axis.title.x = element_blank(),
    text = element_text(family = "Arial", size = 25),  # Set font to Arial
    plot.title = element_text(hjust = 0.5, family = "Arial"),  # Title font
    axis.line = element_line(size = 1.2),
    axis.text = element_text(family = "Arial"),  # Apply Arial to axis text
    axis.title = element_text(family = "Arial")  # Axis title in Arial
  ) +
  guides(fill = FALSE, color = FALSE)  # Remove legend for fill and color
  
  print(plot)

# Set the working directory
setwd("/Users/Elly/Desktop/Kim Lab-Whistler Lab/D3 Behavior Manuscript/PDF figures")

# Save the plot as a PDF
ggsave(
  filename = "fig_S2B.pdf",
  plot = plot,
  device = cairo_pdf,
  width = 5.2,
  height = 8,
  units = "in",
  family = "ArialMT"
)
```

#Figure S2C
```{r}
dmso_quet <- data.frame(cpp_long) %>% filter(group=="dmso-quet")

summary_df <- dmso_quet %>%
  group_by(timepoint, group) %>%
  summarize(
    mean = mean(score, na.rm = TRUE),
    sem = sd(score, na.rm = TRUE) / sqrt(n()),
    .groups = "drop")

plot <- ggplot(dmso_quet, aes(x = timepoint)) +
  geom_bar(aes(y = score, fill = group, color = group, group = timepoint), 
           alpha = 0.5, 
           stat = "summary", 
           position = position_dodge(width = 0.7), 
           fun = "mean", 
           width=0.7) +
  geom_errorbar(data=summary_df, aes(ymin = mean - sem, ymax = mean + sem, color=group, group = timepoint),
                width = 0.2, position = position_dodge(width = 0.7),) +
  geom_path(aes(group = mouse_id, y = score, color = group), alpha = 0.8) +  
    geom_point(aes(y = score, fill = group, group = timepoint, color=group), size = 1, position = position_dodge(width = 0.7), alpha=0.8) +
  scale_color_manual(values = c("dmso-quet"= "forestgreen", "dmso-cloz"= "magenta4")) +
  scale_fill_manual(values = c("dmso-quet"= "forestgreen", "dmso-cloz"= "magenta4")) +
  theme_classic()  +
  scale_y_continuous(limits = c(0, 100), expand = expansion(mult = c(0, 0.02))) +
  ylab("Percent time on Drug side") +
  scale_x_discrete(labels = str_wrap(c("Baseline", "Final Preference"), width = 10)) +
theme(
    axis.text.x = element_text(size = 25, color = "black"),
    axis.ticks.x = element_blank(),
    axis.title.x = element_blank(),
    text = element_text(family = "Arial", size = 25),  # Set font to Arial
    plot.title = element_text(hjust = 0.5, family = "Arial"),  # Title font
    axis.line = element_line(size = 1.2),
    axis.text = element_text(family = "Arial"),  # Apply Arial to axis text
    axis.title = element_text(family = "Arial")  # Axis title in Arial
  ) +
  guides(fill = FALSE, color = FALSE)  # Remove legend for fill and color
  
  print(plot)

# Set the working directory
setwd("/Users/Elly/Desktop/Kim Lab-Whistler Lab/D3 Behavior Manuscript/PDF figures")

# Save the plot as a PDF
ggsave(
  filename = "fig_S2C.pdf",
  plot = plot,
  device = cairo_pdf,
  width = 5.2,
  height = 8,
  units = "in",
  family = "ArialMT"
)
```

#Figure S2D
```{r}
quet_cloz <- data.frame(cpp_long) %>% filter(group=="quet-cloz")

summary_df <- quet_cloz %>%
  group_by(timepoint, group) %>%
  summarize(
    mean = mean(score, na.rm = TRUE),
    sem = sd(score, na.rm = TRUE) / sqrt(n()),
    .groups = "drop")

plot <- ggplot(quet_cloz, aes(x = timepoint)) +
  geom_bar(aes(y = score, fill = group, color = group, group = timepoint), 
           alpha = 0.5, 
           stat = "summary", 
           position = position_dodge(width = 0.7), 
           fun = "mean", 
           width=0.7) +
  geom_errorbar(data=summary_df, aes(ymin = mean - sem, ymax = mean + sem, color=group, group = timepoint),
                width = 0.2, position = position_dodge(width = 0.7),) +
  geom_path(aes(group = mouse_id, y = score, color = group), alpha = 0.8) +  
    geom_point(aes(y = score, fill = group, group = timepoint, color=group), size = 1, position = position_dodge(width = 0.7), alpha=0.8) +
  scale_color_manual(values = c("dmso-quet"= "forestgreen", "quet-cloz"= "magenta4")) +
  scale_fill_manual(values = c("dmso-quet"= "forestgreen", "quet-cloz"= "magenta4")) +
  theme_classic()  +
  scale_y_continuous(limits = c(0, 100), expand = expansion(mult = c(0, 0.02))) +
  ylab("Percent time on Drug side") +
  scale_x_discrete(labels = str_wrap(c("Baseline", "Final Preference"), width = 10)) +
theme(
    axis.text.x = element_text(size = 25, color = "black"),
    axis.ticks.x = element_blank(),
    axis.title.x = element_blank(),
    text = element_text(family = "Arial", size = 25),  # Set font to Arial
    plot.title = element_text(hjust = 0.5, family = "Arial"),  # Title font
    axis.line = element_line(size = 1.2),
    axis.text = element_text(family = "Arial"),  # Apply Arial to axis text
    axis.title = element_text(family = "Arial")  # Axis title in Arial
  ) +
  guides(fill = FALSE, color = FALSE)  # Remove legend for fill and color
  
  print(plot)

# Set the working directory
setwd("/Users/Elly/Desktop/Kim Lab-Whistler Lab/D3 Behavior Manuscript/PDF figures")

# Save the plot as a PDF
ggsave(
  filename = "fig_S2D.pdf",
  plot = plot,
  device = cairo_pdf,
  width = 5.2,
  height = 8,
  units = "in",
  family = "ArialMT"
)
```

#Figure S2E
```{r}
quet_quet <- data.frame(cpp_long) %>% filter(group=="que-quet")

summary_df <- quet_quet %>%
  group_by(timepoint, group) %>%
  summarize(
    mean = mean(score, na.rm = TRUE),
    sem = sd(score, na.rm = TRUE) / sqrt(n()),
    .groups = "drop")

plot <- ggplot(quet_quet, aes(x = timepoint)) +
  geom_bar(aes(y = score, fill = group, color = group, group = timepoint), 
           alpha = 0.5, 
           stat = "summary", 
           position = position_dodge(width = 0.7), 
           fun = "mean", 
           width=0.7) +
  geom_errorbar(data=summary_df, aes(ymin = mean - sem, ymax = mean + sem, color=group, group = timepoint),
                width = 0.2, position = position_dodge(width = 0.7),) +
  geom_path(aes(group = mouse_id, y = score, color = group), alpha = 0.8) +  
    geom_point(aes(y = score, fill = group, group = timepoint, color=group), size = 1, position = position_dodge(width = 0.7), alpha=0.8) +
  scale_color_manual(values = c("que-quet"= "forestgreen", "quet-cloz"= "magenta4")) +
  scale_fill_manual(values = c("que-quet"= "forestgreen", "quet-cloz"= "magenta4")) +
  theme_classic()  +
  scale_y_continuous(limits = c(0, 100), expand = expansion(mult = c(0, 0.02))) +
  ylab("Percent time on Drug side") +
  scale_x_discrete(labels = str_wrap(c("Baseline", "Final Preference"), width = 10)) +
theme(
    axis.text.x = element_text(size = 25, color = "black"),
    axis.ticks.x = element_blank(),
    axis.title.x = element_blank(),
    text = element_text(family = "Arial", size = 25),  # Set font to Arial
    plot.title = element_text(hjust = 0.5, family = "Arial"),  # Title font
    axis.line = element_line(size = 1.2),
    axis.text = element_text(family = "Arial"),  # Apply Arial to axis text
    axis.title = element_text(family = "Arial")  # Axis title in Arial
  ) +
  guides(fill = FALSE, color = FALSE)  # Remove legend for fill and color
  
  print(plot)

# Set the working directory
setwd("/Users/Elly/Desktop/Kim Lab-Whistler Lab/D3 Behavior Manuscript/PDF figures")

# Save the plot as a PDF
ggsave(
  filename = "fig_S2E.pdf",
  plot = plot,
  device = cairo_pdf,
  width = 5.2,
  height = 8,
  units = "in",
  family = "ArialMT"
)
```

#Figure S2 paired t tests
```{r}
t_test_results <- list()

    for (current_group in unique(cpp_long$group)) {
      
      # Subset data for the current treatment, genotype, and drug
      subset_data <- cpp_long[cpp_long$group == current_group, ]
      
        baseline_values <- subset_data$score[subset_data$timepoint == "initial"]
        final_values <- subset_data$score[subset_data$timepoint == "final"]
        
        # Check if we have equal lengths for paired t-test
        if (length(baseline_values) == length(final_values)) {
          # Perform the paired t-test
          t_test_result <- t.test(baseline_values, final_values, paired = TRUE)
          
          # Store results in the list
          t_test_results[[paste(current_group)]] <- t_test_result
        }
      }


# Print the results
print(t_test_results)
```


#Figure 3J (cannula cpa data)
```{r}

setwd("/Users/Elly/Desktop/Kim Lab-Whistler Lab/D3 Behavior Manuscript/")
cpa_cannula <- readxl::read_excel("cannula_cpp_data.xlsx")

pref_combined <- data.frame(cpa_cannula %>%
                dplyr:: select(initial_pref, final_pref, mouse_id, second_time) %>%
      rename(baseline = initial_pref, final = final_pref, second_time = second_time) %>%
      pivot_longer(cols = c(baseline, final, second_time), names_to = "pref", values_to = "percent"))

summary_df <- pref_combined %>%
  group_by(pref) %>%
  summarize(
    mean = mean(percent, na.rm = TRUE),
    sem = sd(percent, na.rm = TRUE) / sqrt(n()))

plot <- ggplot(pref_combined, aes(x=pref)) +
  geom_bar(aes(y = percent), fill="forestgreen", color = "forestgreen",
           alpha = 0.5, 
           stat = "summary", 
           fun = "mean", 
           width=0.7) +
  geom_errorbar(data=summary_df, aes(ymin = mean - sem, ymax = mean + sem), color = "forestgreen",
                width = 0.2) +
  geom_point(aes(y = percent), size = 1, color = "forestgreen") +
  geom_path(aes(group = mouse_id, y = percent), color="forestgreen", alpha = 0.8) +  
  theme_classic()  +
  scale_y_continuous(limits = c(0, 105), expand = c(0, 0)) +
  ylab("Percent time on Drug side") +
  scale_x_discrete(labels = c("Baseline", "0.1 µg", "1 µg")) +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x.bottom = element_text(size = 25, color = "black"),
        axis.title.x= element_blank(),
        text = element_text(size = 25),
        plot.title = element_text(hjust = 0.5), 
        axis.line = element_line(size = 1.2),
        axis.text = element_text(family = "Arial"),  # Apply Arial to axis text
    axis.title = element_text(family = "Arial"))

print(plot)

      # Set the working directory
setwd("/Users/Elly/Desktop/Kim Lab-Whistler Lab/D3 Behavior Manuscript/EPS files")

# Use Cairo EPS device
cairo_ps("fig 3J.eps", width = 8.5, height = 6, family = "ArialMT", pointsize = 12)

# Create the plot
print(plot)

# Close the Cairo EPS device
dev.off()

pref_combined <- pref_combined %>% drop_na()
          
          # Repeated-measures ANOVA
library(lmerTest)
library(emmeans)

# Fit repeated-measures model
rm_model <- lmer(percent ~ pref + (1 | mouse_id), data = pref_combined)

# ANOVA table
anova(rm_model)

# Post-hoc pairwise comparisons with Tukey adjustment
emm <- emmeans(rm_model, ~ pref)
pairwise_result <- pairs(emm, adjust = "tukey")

print(emm)
print(pairwise_result)

# Set the working directory
setwd("/Users/Elly/Desktop/Kim Lab-Whistler Lab/D3 Behavior Manuscript/PDF figures")

# Save the plot as a PDF
ggsave(
  filename = "fig_3J.pdf",
  plot = plot,
  device = cairo_pdf,
  width = 8.5,
  height = 6,
  units = "in",
  family = "ArialMT"
)

write.csv(pref_combined, "pref_combined.csv", row.names = FALSE)
```



#exporting raw data figure 2
```{r}
raw_data <- createWorkbook()

fig_labels <- c("Figure 2A", "Figure 2B", "Figure 2C", "Figure 2D", "Figure 2F acute", "Figure 2F chronic", "Figure 2G acute", "Figure 2G chronic", "Figure 2H acute", "Figure 2H chronic")

dfs_fig <- list(coc_pref, cloz_coc, quet_coc, df_coc, acute_cloz_loc, chronic_cloz_loc, acute_quet_loc, chronic_quet_loc, acute_quet_loc_df, chronic_quet_loc_df)

for (i in 1:length(fig_labels)) {
  current_df <- dfs_fig[[i]]
  
# Check if the 'pref' column exists in the current data frame
  if ("pref" %in% colnames(current_df)) {
    df_wide <- current_df %>%
      pivot_wider(names_from = pref, values_from = percent)
    
    # Add a new worksheet with the custom sheet name
    addWorksheet(raw_data, sheetName = fig_labels[i])
    
    # Write the pivoted data to the worksheet
    writeData(raw_data, sheet = fig_labels[i], df_wide)
    
  } else if ("Drug" %in% colnames(current_df)) {
    # If 'Drug' column exists, pivot wider with 'Drug' as the new columns
    
    df_wide <- current_df %>%
      group_by(Subject, Drug) %>%  # Group by Subject and Drug to ensure proper aggregation
      summarise(Ambulatory_Distance = mean(Ambulatory_Distance, na.rm = TRUE)) %>%  # Aggregate by mean
      pivot_wider(names_from = Drug, values_from = Ambulatory_Distance) %>%
      ungroup()  # Ungroup after pivoting
    
    # Add a new worksheet with the custom sheet name
    addWorksheet(raw_data, sheetName = fig_labels[i])
    
    # Write the pivoted data to the worksheet
    writeData(raw_data, sheet = fig_labels[i], df_wide)
    
  }
}

saveWorkbook(raw_data, "/Users/Elly/Desktop/Kim Lab-Whistler Lab/D3 Behavior Manuscript/writing/raw_data_fig2.xlsx", overwrite = TRUE)
```

