---
output:
  pdf_document: default
  html_document: default
---
#libraries
```{r}
library(tidyverse)
library(tcltk2)
library(lubridate)
library(stringr)
library(dplyr)
library(tidyr)
library(ggplot2)
```

#input files
```{r}
setwd(tk_choose.dir(caption = "Where is your data?"))
filenames <- list.files(getwd())
filenames <- filenames[grepl(".csv$", filenames)]
processed_data <- list()

#blue light or orange light sides
light_side <-c("d3chr1" = "left", "d3chr2" = "right", "d3chr3"="left", "d3chr4"= "left", "d3chr5"="right", "d3chr6" = "right", "d3gcamp27"="right", "d3gcamp28"="left", "d3chr7"="right", "d3chr8"= "right", "d3chr9"="left", "d3chr10"="left", "d3gcamp31"="left", "d3gcamp33"="right", "d3gcamp34"="right", "d1spark1"="left", "d1spark2"="left", "d1spark3"="right", "d1spark4"="right", "d1spark5"="left", "d1spark6"="left", "d1spark7"="right", "d1spark8"="right", "d3chr11"="left", "d3chr12"="left", "d3chr13"="right", "d3chr14"="right", "d3chr15"="right", "d3chr16"="left", "d3chr17"="left", "d3chr18"="left", "wtchr1"="right", "wtchr3"="left", "wtchr4"="right", "wtchr5"="right", "d3gcamp36"="right", "d3gcamp38"="left", "d3gcamp39"="left", "d3chr19"="left", "d3chr20"="right", "d3chr21"="right", "d3chr22"="left", "d3chr26"="right", "d3chr27"="right", "d3chr28"="left", "d3halo1"="left", "d3halo2"="right", "d3halo3"="left", "d3halo4"="right", "d3halo5"="right", "d3halo6"="left", "d3gcamp43"="left", "d3gcamp44"="left", "d3halo7"="left", "d3halo8"="right", "d3halo9"="right", "d3halo10"="right", "wtchr6"="left", "wtchr7"="right", "wtchr8"="right", "wtchr9"="right", "wtchr10"="left", "d3gcamp40"="left", "d3gcamp41"="left", "d3gcamp42"="right", "d3chr24"="right", "d3chr25"="left", "d3chr29"="right", "d3chr23"="right", "D1spark1"="left", "D1spark3"="right", "D1spark4"="left", "D1spark5"="right", "D1spark6"="left", "D1spark7"="right", "d3halo12"="left", "d3halo13"="right", "d3halo14"="left", "d3halo16"="left", "d3halo17"="left", "d3halo18"="right", "d3yfp1"="right", "d3yfp3"="left", "d3yfp4"="right", "d3yfp5"="left", "d3yfp6"="right")

for (i in 1:length(filenames)) {
  
  #import raw .csv
  mouse_raw <- read.csv(filenames[i], header = TRUE, skip = 1)

 #make fresh data frame
  df_raw <- data.frame(time_ms = mouse_raw$TimeStamp[1:nrow(mouse_raw)],
            Events = mouse_raw$Events[1:nrow(mouse_raw)])
  df_raw <- na.omit(df_raw)
 df_raw <- df_raw %>%
  mutate(mins = time_ms/60000) %>%
  mutate(file = filenames[i]) %>%
  extract(file, c("Mouse", "Date", "Treatment"), "([[:alnum:]]+)_([.[:alnum:]]+)_([[:alnum:]]+)", remove = T) %>%
  unite(datemouse, Date, Mouse, remove = F) %>%
  unite(treatmentmouse, Treatment, Mouse, remove = F) %>%
  mutate(Date = mdy(Date)) 
 
  # Add a column for light side for each mouse
  dsdata <- df_raw %>%
    left_join(data.frame(Mouse = names(light_side), light_side = light_side), by = "Mouse")
processed_data[[i]] <- dsdata

}

# ##input track files
setwd(tk_choose.dir(caption = "Where is your data?"))
filenames <- list.files(getwd())
filenames <- filenames[grepl(".csv$", filenames)]
track_data <- list()

for (i in 1:length(filenames)) {

  #import raw .csv
  track_raw <- read.csv(filenames[i], header = TRUE, skip = 1)

  # make fresh data frame
  df_raw <- data.frame(
    time_ms = track_raw$TimeStamp[1:nrow(track_raw)],
    Position = track_raw$Position[1:nrow(track_raw)]
  )
  df_raw <- na.omit(df_raw)
  df_raw <- df_raw %>%
    mutate(mins = time_ms/60000) %>%
    mutate(file = filenames[i]) %>%
    extract(file, c("Mouse", "Date", "Treatment", "Filetype"), "([[:alnum:]]+)_([.[:alnum:]]+)_([[:alnum:]]+)_([.[:alnum:]]+)", remove = T) %>%  unite(datemouse, Date, Mouse, remove = F) %>%
  unite(treatmentmouse, Treatment, Mouse, remove = F) %>%
  mutate(Date = mdy(Date))

  df_raw <- data.frame(df_raw)

  track_data[[i]] <- df_raw %>% left_join(data.frame(Mouse = names(light_side), light_side = light_side), by = "Mouse")
}

all_data_track <- bind_rows(track_data) #could downsample here


all_data_events <- bind_rows(processed_data) %>%
  mutate(
    events = str_extract_all(Events, "ROI1\\*0\\*0|ROI2\\*0\\*0|ROI3\\*0\\*0") %>%
      sapply(function(matches) if(length(matches) > 0) tail(matches, 1) else NA) %>%
      str_replace_all("ROI1\\*0\\*0", "left") %>%
      str_replace_all("ROI2\\*0\\*0", "right") %>%
      str_replace_all("ROI3\\*0\\*0", "doorway")
  ) %>%
  fill(events, .direction = "down")

all_data_events <- bind_rows(all_data_events, all_data_track) %>%
      distinct(time_ms, .keep_all = TRUE)

#duds
duds <- c("d3chr14", "d3halo8", "d3gcamp41", "d3halo17")
all_data_events <- all_data_events %>% arrange(datemouse, time_ms)  %>%
  filter(!str_detect(Mouse, paste(duds, collapse = "|"))) %>%
  fill(events, .direction = "down")  
  

# Create a vector for the second-day light side
#second_day_light_side <- ifelse(light_side == "left", "right", "left")

# Join the second-day light side information to the dataset
# # all_data_events <- all_data_events %>%
#   mutate(second_day_light_side = second_day_light_side[match(Mouse, names(second_day_light_side))])
```

#percent time on light side and separate controls
```{r}
# Initialize the percentage_data data frame
percentage_data <- data.frame()

# Loop through each datemouse
for (current_datemouse in unique(all_data_events$datemouse)) {
  
  # Loop through each treatment for the current datemouse
  for (current_treatment in unique(all_data_events$Treatment[all_data_events$datemouse == current_datemouse])) {
    
    # Subset the data for the current datemouse and treatment
    subset_data <- all_data_events[all_data_events$datemouse == current_datemouse & all_data_events$Treatment == current_treatment, ]
    
    
    # Calculate the percentage of time on the light side for each treatment and mouse
    percentage_time_light_side <- subset_data %>%
      group_by(Mouse, Treatment, light_side, datemouse) %>%
      summarise(PercentageTimeLightSide = sum(events == light_side, na.rm = TRUE) / n(), .groups = 'keep')
    
    # If calculating for second day light side, you would include similar logic:
    # percentage_time_second_day_light_side <- subset_data %>%
    #   group_by(Mouse, Treatment, second_day_light_side, datemouse) %>%
    #   summarise(PercentageTimeSecondDayLightSide = sum(events == second_day_light_side, na.rm = TRUE) / n(), .groups = 'keep')
    
    # Since the second part of the calculation is commented out, we use only the first part here
    combined_percentage <- percentage_time_light_side
    
    # Add to the main data frame
    percentage_data <- bind_rows(percentage_data, combined_percentage)
  }
}

# Print the resulting data frame
print(percentage_data)

    

#separate controls from experimental mice
Group <-c("d3chr1" = "chr", "d3chr2" = "chr", "d3chr3"="chr", "d3chr4"= "chr", "d3chr5"="chr", "d3chr6" = "chr", "d3chr7"="chr", "d3chr8"="chr", "d3chr9"="chr", "d3chr10"="chr", "d3gcamp27"= "yfpblue", "d3gcamp28"="yfpblue", "d3gcamp31"="yfpblue", "d3gcamp33"="yfpblue", "d3gcamp34"="yfpblue","d1spark1"="fentanyl", "d1spark2"="control", "d1spark3"="fentanyl", "d1spark4"="control", "d1spark5"="fentanyl", "d1spark6"="control", "d1spark7"="fentanyl", "d1spark8"="control", "d3chr11"="d3chr", "d3chr12"="d3chr", "d3chr13"="d3chr", "d3chr14"="d3chr", "d3chr15"="d3chr", "d3chr16"="d3chr", "d3chr17"="d3chr", "d3chr18"="d3chr", "wtchr1"="wtchr", "wtchr3"="wtchr", "wtchr4"="wtchr", "wtchr5"="wtchr", "d3gcamp36"="yfpblue", "d3gcamp38"="yfpblue", "d3gcamp39"="yfpblue", "d3chr19"="chr", "d3chr20"="chr", "d3chr21"="chr", "d3chr22"="chr", "d3chr26"="chr", "d3chr27"="chr", "d3chr28"="chr", "d3halo1"="halo", "d3halo2"="halo", "d3halo3"="halo", "d3halo4"="halo", "d3halo5"="halo", "d3halo6"="halo", "d3gcamp43"="yfporange", "d3gcamp44"="yfporange", "d3halo7"="halo", "d3halo8"="halo", "d3halo9"="halo", "d3halo10"="halo", "wtchr8"="wtchr", "wtchr9"="wtchr", "wtchr6"="wtchr", "wtchr7"="wtchr", "wtchr10"="wtchr", "d3gcamp40"="yfpblue", "d3gcamp42"="yfpblue", "d3chr24"="chr", "d3chr25"="chr", "d3chr29"="chr", "d3chr23"="chr", "D1spark1"="fentanyl", "D1spark3"="saline", "D1spark4"="saline", "D1spark5"="fentanyl", "D1spark6"="fentanyl", "D1spark7"="fentanyl", "d3halo12"="halo", "d3halo13"="halo", "d3halo14"="halo", "d3halo16"="halo", "d3halo17"="halo", "d3halo18"="halo")

yfp_group <-c("06122024_d3yfp1"="yfporange", "06122024_d3yfp3"="yfporange", "06122024_d3yfp4"="yfporange", "06122024_d3yfp5"="yfporange", "06122024_d3yfp6"="yfporange", "06132024_d3yfp1"="yfporange", "06132024_d3yfp3"="yfporange", "06132024_d3yfp4"="yfporange", "06132024_d3yfp5"="yfporange", "06132024_d3yfp6"="yfporange", "06142024_d3yfp1"="yfpblue", "06142024_d3yfp3"="yfpblue", "06142024_d3yfp4"="yfpblue", "06142024_d3yfp5"="yfpblue", "06142024_d3yfp6"="yfpblue")

# Add a column for Group to data frame
percentage_data <- percentage_data %>% 
  drop_na(light_side) %>% 
  left_join(data.frame(Mouse = names(Group), Group = Group), by = "Mouse") %>% 
  left_join(data.frame(datemouse = names(yfp_group), yfp_group = yfp_group), by = "datemouse")

#ADD IN FOR DOUBLE YFP MICE

# # Filter rows with Treatment as 'baseline'
# baseline_rows <- percentage_data %>% filter(Treatment == "baseline")
# 
# # Modify the yfp_group column to 'yfpblue'
# baseline_rows$yfp_group <- "yfpblue"
# 
# # Combine the modified rows with the original data
# percentage_data <- bind_rows(percentage_data, baseline_rows)


```

#binned percentage data
```{r}
percentage_bins <- data.frame()

# Create bins
all_data_bins <- all_data_xy %>%
  mutate(bin = cut(mins, breaks = 5))

# Loop through each mouse
for (current_mouse in unique(all_data_bins$Mouse)) {
  
  # Loop through each treatment for the current mouse
  for (current_treatment in unique(all_data_bins$Treatment[all_data_bins$Mouse == current_mouse])) {
    
    # Loop through each bin for the current treatment and mouse
    for (current_bin in unique(all_data_bins$bin[all_data_bins$Mouse == current_mouse & all_data_bins$Treatment == current_treatment])) {
      
      # Subset the data for the current mouse, treatment, and bin
      subset_data <- all_data_bins[all_data_bins$Mouse == current_mouse & all_data_bins$Treatment == current_treatment & all_data_bins$bin == current_bin, ]
      
      # Calculate the percentage of time on the light side for each treatment, mouse, and bin
      percentage_time_light_side_bins <- subset_data %>%
        group_by(Mouse, Treatment, bin, light_side, datemouse) %>%
        summarise(PercentageTimeLightSide = sum(current_side == light_side, na.rm = TRUE) / n(), .groups = 'drop')
      
      # Append to the main data frame
      percentage_bins <- bind_rows(percentage_bins, percentage_time_light_side_bins)
    }
  }
}


#Add a column for Group to the data frame
percentage_bins <- percentage_bins %>%
  left_join(data.frame(Mouse = names(Group), Group = Group), by = "Mouse") %>% 
  left_join(data.frame(Mouse = names(subregion), subregion = subregion), by = "Mouse") %>% 
  left_join(data.frame(Mouse = names(genotype), genotype = genotype), by = "Mouse")

percentage_bins_rtpa <- percentage_bins %>% filter(Treatment=="rtpa")  %>% filter(subregion.x=="lat") %>% filter(Group=="halo")
ggplot(percentage_bins_rtpa, aes(x=bin, y=PercentageTimeLightSide, color=Group)) + geom_boxplot(outlier.shape=NA) + 
  geom_point(aes(group=Group, fill=Group),position=position_jitterdodge(dodge.width = 0.9, jitter.width=0.2)) + 
  theme_classic() +
  geom_line(aes(group = Mouse, color = Group), alpha = 0.4) +
  scale_color_manual(values=c("blue", "orange", "green", "cornflowerblue", "brown")) 


```

#percent time light side graphs 
```{r}

#baseline v day 1 light
percentage_data_rtpa1 <- percentage_data %>% filter(Treatment!="rtpa2") 
ggplot(percentage_data_rtpa1, aes(x=Treatment, y=PercentageTimeLightSide, color=Group)) + geom_boxplot(outlier.shape=NA) + geom_point(aes(group=Group, fill=Group),position=position_jitterdodge(dodge.width = 0.9, jitter.width=0.2)) + 
  theme_classic() +
  scale_color_manual(values=c("blue", "orange", "forestgreen", "cornflowerblue", "brown", "black")) +
  ggtitle("baseline v RTPA1")

#mean instead of median
# Calculate mean values
mean_data <- percentage_data_rtpa1 %>%
  group_by(Treatment, Group) %>%
  summarize(mean_percentage = mean(PercentageTimeLightSide))

# Plot with mean values
ggplot(percentage_data_rtpa1, aes(x=Treatment, y=PercentageTimeLightSide, color=Group)) + 
  geom_boxplot(outlier.shape=NA) + 
  geom_point(data = mean_data, aes(y = mean_percentage, group = Group), 
             position = position_dodge(width = 0.9), color = "black", size = 3, shape = 18) +
  theme_classic() +
  scale_color_manual(values=c("blue", "orange", "forestgreen", "cornflowerblue", "brown")) +
  ggtitle("Baseline v RTPA1")

# new baseline v day 2 light
# percentage_data_rtpa2 <- percentage_data %>% filter(Treatment!="rtpa1")
# ggplot(percentage_data_rtpa2, aes(x=Treatment, y=PercentageTimeSecondDayLightSide, color=Group)) + geom_boxplot(outlier.shape=NA) + geom_point(aes(group=Group, fill=Group),position=position_jitterdodge(dodge.width = 0.9, jitter.width=0.2)) + 
#   theme_classic() +
#   scale_color_manual(values=c("blue", "orange")) +
#   ggtitle("baseline v RTPA2")

#baseline v day 1 light lines
ggplot(data=percentage_data_rtpa1, aes(x = Treatment, y = PercentageTimeLightSide, color = Group)) +
  geom_point( aes(group = Group, fill = Group), position = position_jitterdodge(dodge.width = 0.9, jitter.width = 0.2), size=0.2) +
  geom_text(aes(label = Mouse), position = position_jitterdodge(dodge.width = 0.9, jitter.width = 0.2), vjust = -0.5) + 
  geom_line(aes(x = Treatment, y = PercentageTimeLightSide, group = Mouse), alpha = 0.7) +
  theme_classic() +
  scale_color_manual(values=c("blue", "orange", "forestgreen", "cornflowerblue", "brown")) +
  ggtitle("baseline v RTPA1")

# #baseline v day 2 light lines
# ggplot(data=percentage_data_rtpa2, aes(x = Treatment, y=PercentageTimeSecondDayLightSide, color = Group)) +
#   geom_point( aes(group = Group, fill = Group), position = position_jitterdodge(dodge.width = 0.9, jitter.width = 0.2)) +
#   geom_text(aes(label = Mouse), position = position_jitterdodge(dodge.width = 0.9, jitter.width = 0.2), vjust = -0.5) +  # Add geom_text for Mouse labels 
#   geom_line(aes(x = Treatment, y = PercentageTimeSecondDayLightSide, group = Mouse), alpha = 0.7) +
#   theme_classic() +
#   scale_color_manual(values=c("blue", "orange")) +
#   ggtitle("baseline v RTPA2")


#sleeping mice identifier
#percentage_data <- percentage_data %>% 
  #mutate(sleeping_mice = case_when(
    #(str_detect(Mouse, "d3chr11") == TRUE | 
     #str_detect(Mouse, "d3chr12") == TRUE | 
     #str_detect(Mouse, "d3chr13") == TRUE | 
     #str_detect(Mouse, "d3chr14") == TRUE) & str_detect(Treatment, "rtpa") ~ TRUE,
    #TRUE ~ FALSE
  #))

# set.seed(27)
 ggplot(percentage_data, aes(x = Treatment, y = PercentageTimeLightSide)) +
  geom_boxplot(aes(fill=Group), outlier.shape = NA, alpha=0.8) +
  geom_jitter(aes(group = Group, color=Group), position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.9)) + theme_classic() +
  scale_fill_manual(values=c("chr"= "blue", "wtchr"= "forestgreen", "control"="orchid")) +
  scale_color_manual(values = c("TRUE" = "red", "FALSE" = "black"))

#t-test
# Subset your data
group_data_chr <- subset(percentage_data, Group == "chr")
group_data_halo <- subset(percentage_data, Group == "halo")
treatment_data_rtpa1 <- subset(percentage_data, Treatment == "rtpa1")

# Split the data for each treatment
treatment_baseline <- group_data_chr[group_data_chr$Treatment == "baseline", "PercentageTimeLightSide"]
treatment_rtpa1 <- group_data_chr[group_data_chr$Treatment == "rtpa1", "PercentageTimeLightSide"]
# Perform t-test
t_test_result_chr <- t.test(treatment_baseline, treatment_rtpa1)
# Print the result
print(t_test_result_chr)

# Split the data for each treatment
treatment_baseline <- group_data_halo[group_data_halo$Treatment == "baseline", "PercentageTimeLightSide"]
treatment_rtpa1 <- group_data_halo[group_data_halo$Treatment == "rtpa1", "PercentageTimeLightSide"]
# Perform t-test
t_test_result_halo <- t.test(treatment_baseline, treatment_rtpa1)
# Print the result
print(t_test_result_halo)

# Split the data for each group
group_chr <- treatment_data_rtpa1[treatment_data_rtpa1$Group == "chr", "PercentageTimeLightSide"]
group_halo <- treatment_data_rtpa1[treatment_data_rtpa1$Group == "halo", "PercentageTimeLightSide"]
# Perform t-test
t_test_result_rtpa1 <- t.test(group_chr, group_halo)
# Print the result
print(t_test_result_rtpa1)

#separate controls from experimental mice
combined_controls <-c("d3chr1" = "chr", "d3chr2" = "chr", "d3chr3"="chr", "d3chr4"= "chr", "d3chr5"="chr", "d3chr6" = "chr", "d3chr7"="chr", "d3chr8"="chr", "d3chr9"="chr", "d3chr10"="chr", "d3gcamp27"= "control", "d3gcamp28"="control", "d3gcamp31"="control", "d3gcamp33"="control", "d3gcamp34"="control","d1spark1"="fentanyl", "d1spark2"="control", "d1spark3"="fentanyl", "d1spark4"="control", "d1spark5"="fentanyl", "d1spark6"="control", "d1spark7"="fentanyl", "d1spark8"="control", "d3chr11"="d3chr", "d3chr12"="d3chr", "d3chr13"="d3chr", "d3chr14"="d3chr", "d3chr15"="d3chr", "d3chr16"="d3chr", "d3chr17"="d3chr", "d3chr18"="d3chr", "wtchr1"="wtchr", "wtchr3"="wtchr", "wtchr4"="wtchr", "wtchr5"="wtchr", "d3gcamp36"="yfpcontrol", "d3gcamp38"="yfpcontrol", "d3gcamp39"="yfpcontrol", "d3chr19"="chr", "d3chr20"="chr", "d3chr21"="chr", "d3chr22"="chr", "d3chr26"="chr", "d3chr27"="chr", "d3chr28"="chr", "d3halo1"="halo", "d3halo2"="halo", "d3halo3"="halo", "d3halo4"="halo", "d3halo5"="halo", "d3halo6"="halo", "d3gcamp43"="yfp", "d3gcamp44"="yfp", "d3halo7"="halo", "d3halo8"="halo", "d3halo9"="halo", "d3halo10"="halo", "wtchr8"="wtchr", "wtchr9"="wtchr", "wtchr6"="wtchr", "wtchr7"="wtchr", "wtchr10"="wtchr", "d3gcamp40"="yfp", "d3gcamp42"="yfp", "d3chr24"="chr", "d3chr25"="chr", "d3chr29"="chr", "d3chr23"="chr")

 # Add a column for combined_controls to data frame
  percentage_data <- percentage_data %>% drop_na(light_side)  %>% 
    left_join(data.frame(Mouse = names(combined_controls), combined_controls = combined_controls), by = "Mouse")


percentage_data_rtpa1 <- percentage_data %>% filter(Treatment!="rtpa2") 
ggplot(percentage_data_rtpa1, aes(x=Treatment, y=PercentageTimeLightSide, color=combined_controls)) + geom_boxplot(outlier.shape=NA) + geom_point(aes(group=combined_controls, fill=combined_controls),position=position_jitterdodge(dodge.width = 0.9, jitter.width=0.2)) + 
  theme_classic() +
  scale_color_manual(values=c("blue", "orange", "forestgreen", "orchid")) +
  ggtitle("baseline v RTPA1")

#means 
mean_data <- percentage_data_rtpa1 %>% 
  dplyr:: select(Treatment, PercentageTimeLightSide, Mouse, combined_controls) %>%
   group_by(Treatment, combined_controls) %>% add_tally(sort = FALSE, name = "n") %>% 
  mutate(mean=mean(PercentageTimeLightSide), na.rm=TRUE) %>%
  mutate(sd=sd(PercentageTimeLightSide)) %>% mutate(sem=sd/sqrt(n)) %>%
  ungroup() 

ggplot(mean_data, aes(x=Treatment, color=combined_controls, group= combined_controls)) +
  geom_point(aes(y=PercentageTimeLightSide, fill=combined_controls), size= 0.5, position=position_jitterdodge(dodge.width = 0.6, jitter.width=0.2)) +
  geom_point(aes(y=mean, fill=combined_controls, color=combined_controls), size= 3, position=position_dodge(width=0.5), shape=18) +
  geom_errorbar(aes(ymin=mean-sem, ymax=mean+sem), width=0.4, position=position_dodge(width=0.5)) +
  theme_classic () +
  scale_color_manual(values=c("blue", "orange", "forestgreen", "orchid")) +
  ggtitle("baseline v RTPA1")
  
```

#time on each side graphs
```{r}
time_each_side <- all_data_events %>% group_by(Mouse, Treatment, events) %>% summarise(count=n()) %>% ungroup() %>% mutate(time_mins=count * 0.00333333)
time_each_side <- time_each_side %>%
  left_join(data.frame(Mouse = names(Group), Group = Group), by = "Mouse")
  
#bin the data
all_data_bins <- all_data_events %>% mutate(bin = cut(all_data_events$mins, breaks = 5))
time_each_side_bins <- all_data_bins %>% group_by(Mouse, Treatment, bin, events) %>% summarise(count=n()) %>% ungroup() %>% mutate(time_mins=count * 0.00333333)
time_each_side_bins <- time_each_side_bins %>%
  left_join(data.frame(Mouse = names(Group), Group = Group), by = "Mouse")

ggplot(time_each_side, aes(x=events, y=time_mins)) +
  geom_boxplot(aes(fill=Group), outlier.shape=NA, alpha=0.5) +
  theme_classic() +
  geom_jitter(aes(group = Group, color=Mouse), position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.9))
  

time_each_side_rtpa_bins <- time_each_side_bins %>% filter(Treatment=="rtpa1")
ggplot(time_each_side_rtpa_bins, aes(x=bin, y=time_mins)) +
  geom_boxplot(aes(fill=events), color="gray", outlier.shape=NA, alpha=0.5) +
  theme_classic() +
  geom_jitter(aes(group = events, color= Group), position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.9), size=0.2) +
  scale_color_manual(values=c("blue", "orange")) 
#+ geom_text(aes(label = Mouse, color = events), position = position_jitterdodge(dodge.width = 0.9, jitter.width = 0.2), vjust = -0.5, size=3)

ggplot(time_each_side_rtpa, aes(x=events, y=time_mins)) +
  geom_boxplot(aes(fill=Group), outlier.shape=NA, alpha=0.5) +
  theme_classic() +
  geom_jitter(aes(group = Group, color=Group), position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.9)) 

time_each_side_bins_rtpa <- time_each_side_bins %>% filter(Treatment=="rtpa1")
ggplot(time_each_side_bins_rtpa, aes(x=bin, y=time_mins)) +
  geom_boxplot(aes(fill=events), outlier.shape=NA, alpha=0.5) +
  theme_classic() +
  geom_jitter(aes(group = events, color=events), position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.9)) +
  ggtitle("RTPA1")
  
```

#last 25 mins only
```{r}
percentage_data_25 <- data.frame()

# Loop through each mouse
for (current_mouse in unique(all_data_events$Mouse)) {
  
  # Loop through each treatment for the current mouse
  for (current_treatment in unique(all_data_events$Treatment[all_data_events$Mouse == current_mouse])) {
    
     # Subset the data for the current mouse and treatment
    subset_data <- all_data_events[all_data_events$Mouse == current_mouse & all_data_events$Treatment == current_treatment & all_data_events$mins > 5, ]
    
    # Calculate the percentage of time on the light side for each treatment and mouse
    percentage_time_light_side <- subset_data %>%
      group_by(Mouse, Treatment, light_side) %>%
      summarise(PercentageTimeLightSide = sum(events == light_side, na.rm = TRUE) / n(), .groups = 'keep')
    
    # Calculate the percentage of time on the second-day light side for each treatment and mouse
    percentage_time_second_day_light_side <- subset_data %>%
      group_by(Mouse, Treatment, second_day_light_side) %>%
      summarise(PercentageTimeSecondDayLightSide = sum(events == second_day_light_side, na.rm = TRUE) / n(), .groups = 'keep')
    
   # Combine the two data frames into one by joining on Mouse and Treatment
    combined_percentage <- left_join(percentage_time_light_side, percentage_time_second_day_light_side, by = c("Mouse", "Treatment"))
    
    # Add to the main data frame
    percentage_data_25 <- bind_rows(percentage_data_25, combined_percentage)
  }
}

# Add a column for Group to data frame
  percentage_data_25 <- percentage_data_25 %>%
    left_join(data.frame(Mouse = names(Group), Group = Group), by = "Mouse") 
  
  #baseline v day 1 light
percentage_data_rtpa1_25 <- percentage_data_25 %>% filter(Treatment!="rtpa2") %>% filter(Mouse!="d3chr3")
ggplot(percentage_data_rtpa1_25, aes(x=Treatment, y=PercentageTimeLightSide, color=Group)) + geom_boxplot(outlier.shape=NA) + geom_point(aes(group=Group, fill=Group),position=position_jitterdodge(dodge.width = 0.9, jitter.width=0.2)) + 
  theme_classic() +
  scale_color_manual(values=c("blue", "orange", "forestgreen")) +
  ggtitle("baseline v RTPA1")

# # new baseline v day 2 light
# percentage_data_rtpa2_25 <- percentage_data_25 %>% filter(Treatment!="rtpa1")
# ggplot(percentage_data_rtpa2_25, aes(x=Treatment, y=PercentageTimeSecondDayLightSide, color=Group)) + geom_boxplot(outlier.shape=NA) + geom_point(aes(group=Group, fill=Group),position=position_jitterdodge(dodge.width = 0.9, jitter.width=0.2)) + 
#   theme_classic() +
#   scale_color_manual(values=c("blue", "orange")) +
#   ggtitle("baseline v RTPA2")

#baseline v day 1 light lines
ggplot(data=percentage_data_rtpa1_25, aes(x = Treatment, y = PercentageTimeLightSide, color = Group)) +
  geom_point( aes(group = Group, fill = Group), position = position_jitterdodge(dodge.width = 0.9, jitter.width = 0.2)) +
  geom_text(aes(label = Mouse), position = position_jitterdodge(dodge.width = 0.9, jitter.width = 0.2), vjust = -0.5) +  # Add geom_text for Mouse labels 
  geom_line(aes(x = Treatment, y = PercentageTimeLightSide, group = Mouse), alpha = 0.7) +
  theme_classic() +
  scale_color_manual(values=c("blue", "orange", "forestgreen")) +
  ggtitle("baseline v RTPA1")

# #baseline v day 2 light lines
# ggplot(data=percentage_data_rtpa2_25, aes(x = Treatment, y=PercentageTimeSecondDayLightSide, color = Group)) +
#   geom_point( aes(group = Group, fill = Group), position = position_jitterdodge(dodge.width = 0.9, jitter.width = 0.2)) +
#   geom_text(aes(label = Mouse), position = position_jitterdodge(dodge.width = 0.9, jitter.width = 0.2), vjust = -0.5) +  # Add geom_text for Mouse labels 
#   geom_line(aes(x = Treatment, y = PercentageTimeSecondDayLightSide, group = Mouse), alpha = 0.7) +
#   theme_classic() +
#   scale_color_manual(values=c("blue", "orange")) +
#   ggtitle("baseline v RTPA2")

#t-test
# Subset your data
group_data_chr <- subset(percentage_data_25, Group == "chr")
group_data_halo <- subset(percentage_data_25, Group == "halo")
treatment_data_rtpa1 <- subset(percentage_data_25, Treatment == "rtpa1")

# Split the data for each treatment
treatment_baseline <- group_data_chr[group_data_chr$Treatment == "baseline", "PercentageTimeLightSide"]
treatment_rtpa1 <- group_data_chr[group_data_chr$Treatment == "rtpa1", "PercentageTimeLightSide"]
# Perform t-test
t_test_result_chr <- t.test(treatment_baseline, treatment_rtpa1)
# Print the result
print(t_test_result_chr)

# Split the data for each treatment
treatment_baseline <- group_data_halo[group_data_halo$Treatment == "baseline", "PercentageTimeLightSide"]
treatment_rtpa1 <- group_data_halo[group_data_halo$Treatment == "rtpa1", "PercentageTimeLightSide"]
# Perform t-test
t_test_result_halo <- t.test(treatment_baseline, treatment_rtpa1)
# Print the result
print(t_test_result_halo)

# Split the data for each group
group_chr <- treatment_data_rtpa1[treatment_data_rtpa1$Group == "chr", "PercentageTimeLightSide"]
group_halo <- treatment_data_rtpa1[treatment_data_rtpa1$Group == "halo", "PercentageTimeLightSide"]
# Perform t-test
t_test_result_rtpa1 <- t.test(group_chr, group_halo)
# Print the result
print(t_test_result_rtpa1)

```

#x and y 
```{r}

light_color <- c("chr"= "blue", "wtchr"="blue", "yfporange"="orange", "halo"="orange", "yfpblue"="blue", "fentanyl"="blue", "saline"="blue"
# Individual Mouse traces
unique_datemouse <- unique(all_data_xy$datemouse)

for (i in 1:length(unique_datemouse)) {
  treatment <- unique_datemouse[i]
  subset_data <- all_data_xy[all_data_xy$datemouse == treatment,]
  
plot <- ggplot(subset_data, aes(x = X, y = Y)) +
  geom_rect(aes(fill=light_color),
              xmin = if_else(subset_data$light_side == "left", 0, 800),
              xmax = if_else(subset_data$light_side == "left", 800, Inf),
              ymin = -Inf, ymax = Inf, alpha = 0.8) +
  scale_fill_manual(values=light_color) +
    geom_path() +
    theme_classic() + 
    ggtitle(paste("Treatment:", treatment))
  
  print(plot)
}

#heatmap
unique_treatmentmouse <- unique(all_data_xy$treatmentmouse)
colors <- c("deepskyblue", "green", "yellow", "red")

for (i in 1:length(unique_treatmentmouse)) {
  treatment <- unique_treatmentmouse[i]
  subset_data <- all_data_xy[all_data_xy$treatmentmouse == treatment,]
  
  plot <- ggplot(subset_data, aes(x = X, y = Y)) +
    stat_density_2d(aes(fill = ..level..), geom = "polygon", alpha = 0.6) +  # Use stat_density_2d with geom = "polygon" for filled contours
    scale_fill_gradientn(colors = colors, limits = c(0, NA)) +  # Set gradient colors
    theme_classic() + 
    theme(panel.background = element_rect(fill = "deepskyblue")) +
    ggtitle(paste("Heatmap for Treatment:", treatment))  # Set the title
  
  print(plot)
}

```

#locomotion
```{r}
euclidean_distance <- function (X1, Y1, X2, Y2) {
  
  return(sqrt(abs((X2-X1)^2 + (Y2-Y1)^2)))
  
}
  
accurate_tracking_data <- all_data_xy %>%
  mutate(accurate_tracking = case_when(
    str_detect(Mouse, "d3chr29") |
    str_detect(Mouse, "d3halo7") &
    str_detect(Treatment, "baseline") ~ FALSE, 
    str_detect(Mouse, "d3chr28") |
    str_detect(Mouse, "d3halo3") &
    str_detect(Treatment, "rtpa1") ~ FALSE,
    TRUE ~ TRUE # Set other cases to TRUE, meaning they are accurate_tracking
  )) %>% filter((accurate_tracking)) 

# Keep the first row for each treatmentmouse group and then every 13th row
downsampled_data <- accurate_tracking_data %>%
  group_by(treatmentmouse) %>%
  slice(c(1, seq(13, n(), by = 13))) 

# Initialize a list to store the total locomotion for each datemouse entry
total_locomotion <- vector("numeric", length = length(unique(downsampled_data$treatmentmouse)))

# Loop through each unique datemouse entry
for (i in seq_along(unique(downsampled_data$treatmentmouse))) {
  treatmentmouse_entry <- unique(downsampled_data$treatmentmouse)[i]
  
  # Subset the data for the current datemouse entry
  subset_data <- downsampled_data[downsampled_data$treatmentmouse == treatmentmouse_entry, ]
  
  # Displacement for each time step within the subset
  displacement <- c(0) # Displacement at t=0 is 0
  length [i] <- length(subset_data$time_ms)
  
  for (j in 2:nrow(subset_data)) { 
    each_displacement <- euclidean_distance(subset_data$X[j-1], subset_data$Y[j-1], subset_data$X[j], subset_data$Y[j])
    displacement <- c(displacement, each_displacement)
       
  }
  
  # Calculate the total locomotion for the current datemouse entry
  total_locomotion[i] <- sum(displacement, na.rm=TRUE)
  
}

# Create a data frame with treatmentmouse and total locomotion
total_locomotion_df <- data.frame(
  treatmentmouse = unique(downsampled_data$treatmentmouse),
  total_locomotion = total_locomotion
)

percentage_data_rtpa1 <- percentage_data_rtpa1 %>%  unite(treatmentmouse, Treatment, Mouse, remove = F)
total_locomotion <- left_join(total_locomotion_df, percentage_data_rtpa1, by = "treatmentmouse") %>% drop_na(Group) 


ggplot(total_locomotion, aes(x=Treatment, y=total_locomotion, color=Group)) +
  geom_boxplot(outlier.shape=NA) +
  theme_classic() +
  geom_point(aes(fill=Group, group=Group), position=position_jitterdodge(dodge.width = 0.9, jitter.width=0.2)) +
  scale_color_manual(values=c("blue", "orange", "forestgreen", "cornflowerblue", "brown")) +
  ggtitle("Total Locomotion")
```
#figures for paper
```{r}
chr_d3only <- percentage_data %>% filter(Group == "chr") %>% filter(Treatment!="rtpa2") 
yfp_only <-  percentage_data %>% filter(Group == "yfpblue" | Group == "yfporange") %>% filter(Treatment!="rtpa2") 

# mean_d3only <- d3only %>% 
#   dplyr:: select(Mouse, Treatment, Group, PercentageTimeLightSide) %>%
#   group_by(Treatment, Group) %>% 
#   add_tally(sort = FALSE, name = "n") %>% 
#   mutate(mean=mean(PercentageTimeLightSide), na.rm=TRUE) %>%
#   mutate(sd=sd(PercentageTimeLightSide)) %>% mutate(sem=sd/sqrt(n)) %>%
#   ungroup() 

##t-tests run above
# Extract p-values
p_value_chr <- t_test_result_chr$p.value
p_value_halo <- t_test_result_halo$p.value
p_value_rtpa1 <- t_test_result_rtpa1$p.value


ggplot(yfp_only, aes(x = Treatment)) +
  geom_point(aes(y = PercentageTimeLightSide, fill = Group, color = Group), size = 0.5) +
  geom_path(aes(group = Mouse, y = PercentageTimeLightSide, color = Group), alpha = 0.5) +  
  theme_classic() +
  scale_color_manual(values = c("yfpblue" = "goldenrod", "yfporange"="goldenrod")) +
  scale_y_continuous(limits = c(0, 0.8), expand = c(0, 0)) +
  ylab("Fraction of time on LED ON side") +
  scale_x_discrete(labels = c("Baseline Day", "Real Time Place")) +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x.bottom = element_text(size = 10, color = "black"),
        axis.title.x= element_blank(),
        text = element_text(size = 17),
        plot.title = element_text(hjust = 0.5)) +
  ggtitle("Lateral NAsh: YFP") +
   guides(fill = FALSE, color = FALSE)  # Remove legend for fill and color

```

#filter for tracking working
```{r}

# Define the Euclidean distance function
euclidean_distance <- function(Position1, Position2) {
  # Parse x and y coordinates from Position strings
  Position1 <- as.numeric(strsplit(as.character(Position1), ";")[[1]])
  Position2 <- as.numeric(strsplit(as.character(Position2), ";")[[1]])
  
  return(sqrt(sum((Position2 - Position1)^2)))
}

angle <- function(Position1, Position2, Position3) {
  # Parse coordinates from Position strings
  Position1 <- as.numeric(strsplit(Position1, ";")[[1]])
  Position2 <- as.numeric(strsplit(Position2, ";")[[1]])
  Position3 <- as.numeric(strsplit(Position3, ";")[[1]])

  # If displacement from Position1 to Position2 is zero, use previous row's Position1
  if (all(Position1 == Position2)) {
    Position1 <- as.numeric(strsplit(Position2, ";")[[1]])
    Position2 <- as.numeric(strsplit(Position3, ";")[[1]])
  }

  # Calculate vectors
  vec1 <- Position1 - Position2
  vec2 <- Position3 - Position2

  # Calculate magnitudes
  mag1 <- sqrt(sum(vec1^2))
  mag2 <- sqrt(sum(vec2^2))

  # Calculate dot product
  dot_prod <- sum(vec1 * vec2)

  # Calculate angle (in radians)
  angle_radians <- acos(dot_prod / (mag1 * mag2))

  # Convert angle to degrees
  angle_degrees <- angle_radians * (180 / pi)

  return(angle_degrees)
}

# Loop through each unique treatmentmouse entry
for (i in seq_along(unique(all_data_xy$treatmentmouse))) {
  treatmentmouse_entry <- unique(all_data_xy$treatmentmouse)[i]
  
  # Subset the data for the current treatmentmouse entry
  subset_data <- all_data_xy[all_data_xy$treatmentmouse == treatmentmouse_entry, ]
  
  # Calculate each displacement for each row
  subset_data$each_displacement <- c(NA, sapply(2:nrow(subset_data), function(j) {
    euclidean_distance(subset_data$Position[(j-1)], subset_data$Position[j])
  }))
  
  # Calculate angles between consecutive points
  subset_data$each_angle <- c(NA, NA, sapply(3:nrow(subset_data), function(j) {
    angle(subset_data$Position[(j-2)], subset_data$Position[(j-1)], subset_data$Position[j])
  }))
  
  # Filter the subset based on displacement criteria
  good_track_df <- subset_data %>%
    mutate(good_track = each_displacement < 100) %>%
    filter(good_track) %>% mutate(X = as.numeric(str_extract(Position, "\\d+(?=;)")),   Y = as.numeric(str_extract(Position, "(?<=;)\\d+"))) 
  
  #filter for angle is 0 but displacement isn't
  good_track_df <- good_track_df %>% mutate(long_segment = case_when(
    each_angle != 0 &
      each_displacement > 1 & each_displacement < 10 ~ TRUE,
    TRUE ~ FALSE
  )) %>% filter(!long_segment) %>% filter(!is.nan(each_angle)) %>%
    filter(each_angle != 90) %>%
    filter(each_angle != 45)
  
# Identify rows where events change from 'left' to 'right' or 'right' to 'left'
change_sides <- which(good_track_df$events[-1] != good_track_df$events[-nrow(good_track_df)]) + 1
# Use case_when to create a new column not_doorway
good_track_df <- good_track_df %>%
  mutate(not_doorway = case_when(
    row_number() %in% change_sides & Y > 400 & Y < 500 ~ TRUE,
    TRUE ~ FALSE
  ))

# Filter out the rows where not_doorway is TRUE
good_track_df <- good_track_df %>%
  filter(!not_doorway) %>%
  select(-not_doorway)  # Optionally remove the helper column

  
  # Store or process 'good_track_df' as needed (list)

}

# Individual Mouse traces
unique_treatmentmouse <- unique(good_track_df$treatmentmouse)

for (i in 1:length(unique_treatmentmouse)) {
  treatment <- unique_treatmentmouse[i]
  subset_data <- good_track_df[good_track_df$treatmentmouse == treatment,]
  
plot <- ggplot(subset_data, aes(x = X, y = Y)) +
  geom_rect(aes(fill=Group),
              xmin = if_else(subset_data$light_side == "left", 0, 800),
              xmax = if_else(subset_data$light_side == "left", 800, Inf),
              ymin = -Inf, ymax = Inf, alpha = 0.8) +
  scale_fill_manual(values=light_color) +
    geom_path(aes(color=each_displacement)) +
    scale_color_gradient2(limits = c(0, 25), breaks = seq(0, 25, 5))+
    theme_classic() + 
    ggtitle(paste("Treatment:", treatment))
  
  print(plot)
}
#populate events after this

#graph each_displacement over time
ggplot(subset_data, aes(x=mins, y=each_displacement)) +
  geom_line()

ggplot(good_track_df, aes(x=each_displacement, y= each_angle)) +
  geom_line()

```

#stats
```{r}
# For the 'chr' group
chr_data <- subset(percentage_xy, Group == "chr", subregion =="lat")
anova_chr <- aov(PercentageTimeLightSide ~ Treatment, data = chr_data)
summary(anova_chr)

# For the 'halo' group
halo_data <- subset(percentage_xy, Group == "halo")
anova_halo <- aov(PercentageTimeLightSide ~ Treatment, data = halo_data)
summary(anova_halo)

# Two-way ANOVA
two_way_anova <- aov(PercentageTimeLightSide ~ Treatment * Group, data = percentage_xy)
summary(two_way_anova)

# Two-way ANOVA YFP mice
two_way_anova <- aov(PercentageTimeLightSide ~ Treatment * yfp_group, data = percentage_xy)
summary(two_way_anova)

# For the 'orange' group
orange_data <- subset(percentage_xy, yfp_group == "yfporange")
anova_orange <- aov(PercentageTimeLightSide ~ Treatment, data = orange_data)
summary(anova_orange)
```

#percent time light side from X coordinate
```{r}
# Extract X and Y coordinates, join with Group, and categorize sides
all_data_xy <- all_data_events %>%
  mutate(X = as.numeric(str_extract(Position, "\\d+(?=;)")),   
         Y = as.numeric(str_extract(Position, "(?<=;)\\d+"))) %>%
  drop_na(Position) %>%
  mutate(current_side = case_when(
    X > 700 ~ "right",
    X < 600 ~ "left",
    X >= 600 & X <= 700 ~ "doorway"
  ))

# Initialize an empty data frame to store results
percentage_xy <- data.frame()

# Loop through each mouse
for (current_datemouse in unique(all_data_xy$datemouse)) {
  
  # Loop through each treatment for the current mouse
  for (current_treatment in unique(all_data_xy$Treatment[all_data_xy$datemouse == current_datemouse])) {
    
    # Subset the data for the current mouse and treatment
    subset_data <- all_data_xy[all_data_xy$datemouse == current_datemouse & all_data_xy$Treatment == current_treatment, ]
    
    # Calculate the percentage of time on the light side for each treatment and mouse
    #put genotype back in and Group and subregion in group_by
    percentage_temp <- subset_data %>%
      group_by(Mouse, Treatment, light_side, datemouse) %>%
      summarise(PercentageTimeLightSide = sum(current_side == light_side, na.rm = TRUE) / n(), .groups = 'keep')
    
    # Append results to percentage_xy
    percentage_xy <- bind_rows(percentage_xy, percentage_temp)
  }
}

# Add a column for Group to the data frame
percentage_xy <- percentage_xy %>%
  drop_na(light_side) %>% 
  left_join(data.frame(Mouse = names(Group), Group = Group), by = "Mouse") %>% 
  left_join(data.frame(datemouse = names(yfp_group), yfp_group = yfp_group), by = "datemouse")

# Filter rows with Treatment as 'baseline'
baseline_rows <- percentage_xy %>% filter(Treatment == "baseline")

# Modify the yfp_group column to 'yfpblue'
baseline_rows$yfp_group <- "yfpblue"

# Combine the modified rows with the original data
percentage_xy <- bind_rows(percentage_xy, baseline_rows)
```

#percent graphs from XY
```{r}
halo_d3only <- percentage_xy %>% filter(Group == "halo")

ggplot(halo_d3only, aes(x = Treatment, fill=Group, color = Group)) +
  geom_point(aes(y = PercentageTimeLightSide), size = 0.5) +
  geom_path(aes(group = Mouse, y = PercentageTimeLightSide), alpha = 0.5) +  
  theme_classic() +
  scale_y_continuous(limits = c(0, 1.0), expand = c(0, 0)) +
  ylab("Fraction of time on LED ON side") +
  scale_x_discrete(labels = c("Baseline Day", "Real Time Place")) +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x.bottom = element_text(size = 10, color = "black"),
        axis.title.x= element_blank(),
        text = element_text(size = 17),
        plot.title = element_text(hjust = 0.5)) +
  ggtitle("Medial Nacsh: D1 cre Spark") +
   guides(fill = FALSE, color = FALSE)  # Remove legend for fill and color
```

#double YFP specific
```{r}
#from events
ggplot(data=percentage_data, aes(x = Treatment, y = PercentageTimeLightSide, color = yfp_group)) +
  geom_point( aes(group = yfp_group, fill = yfp_group)) +
  geom_text(aes(label = Mouse), position = position_jitterdodge(dodge.width = 0.9, jitter.width = 0.2), vjust = -0.5) + 
  geom_line(aes(x = Treatment, y = PercentageTimeLightSide, group = Mouse), alpha = 0.7) +
  theme_classic() 

# Sort the data by Mouse and Treatment
percentage_xy <- percentage_xy %>%
  arrange(Mouse, datemouse)

#from xy
ggplot(percentage_xy, aes(x = Treatment, y = PercentageTimeLightSide,)) +
  geom_point(aes( fill = yfp_group, color = yfp_group), size = 0.5) +
  geom_line(aes(group = interaction(Mouse, yfp_group), color = yfp_group), alpha = 0.5) +  
  theme_classic() +
  scale_color_manual(values = c("yfporange"="orange", "yfpblue"="blue"), "halo"="orange") +
  scale_y_continuous(limits = c(0, 1.0), expand = c(0, 0)) +
  ylab("Fraction of time on LED ON side") +
  scale_x_discrete(labels = c("Baseline Day", "Real Time Place")) +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x.bottom = element_text(size = 15, color = "black"),
        axis.title.x= element_blank(),
        text = element_text(size = 17),
        plot.title = element_text(hjust = 0.5)) +
  ggtitle("Lateral Nacsh: eYFP") +
   guides(fill = FALSE, color = FALSE)  # Remove legend for fill and color

ggplot(subset_data, aes(x = X, y = Y)) +
    geom_path() +
    theme_classic() + 
    ggtitle(paste("Treatment:", treatment))

```

